package consts

const (
	HOST_LOOPBACK_ADDR string = "127.0.0.1"
	LOG_MODEL_NAME     string = "web"
)

const (
	LOG_LEVEL_EMERGENCY int = 0
	LOG_LEVEL_ALERT         = 1
	LOG_LEVEL_CRITICAL      = 2
	LOG_LEVEL_ERROR         = 3
	LOG_LEVEL_WARNING       = 4
	LOG_LEVEL_NOTICE        = 5
	LOG_LEVEL_INFO          = 6
	LOG_LEVEL_DEBUG         = 7
)

const (
	RESULT_SUCCESS int = 0
	//系统通用错误，1-199
	RESULT_ERROR_COMMON              int = 1
	RESULT_ERROR_NULL_POINTER        int = 2
	RESULT_ERROR_NOT_FOUND           int = 3
	RESULT_ERROR_ALREADY_EXIST       int = 4
	RESULT_ERROR_OUTOF_MEMORY        int = 5
	RESULT_ERROR_TIME_OUT            int = 6
	RESULT_ERROR_FILE_NOT_FOUND      int = 7
	RESULT_ERROR_FAILED_OPEN_FILE    int = 8
	RESULT_ERROR_DISK_FULL           int = 9
	RESULT_ERROR_NO_PERMISSION       int = 10
	RESULT_ERROR_INVALID_PARAM       int = 11
	RESULT_ERROR_CPU_OVERLOAD        int = 12
	RESULT_ERROR_LOAD_MODULE         int = 13
	RESULT_ERROR_INVALID_UUID_STRING int = 14
	RESULT_ERROR_INVALID_DATE_FORMAT int = 15
	RESULT_ERROR_FAILED_ENCODING     int = 16
	RESULT_ERROR_FAILED_DECODING     int = 17
	RESULT_ERROR_NOT_IMPLEMENTED     int = 18
	RESULT_ERROR_SYSCALL_FAIL        int = 19
	RESULT_ERROR_QUOTA_EXCEEDED      int = 20
	RESULT_ERROR_NOT_INITIATED       int = 21
	//Error for sysmgr,暂时保留，不应该给具体某个模块预留错误，而是给功能错误留错误码，未初始化则对所有的系统都应未初始化
	RESULT_ERROR_SYSMGR_NOT_INITED      int = 196
	RESULT_ERROR_SYSMRG_UPDATEREQ       int = 197
	RESULT_ERROR_SYSMRG_CANCELUPDATEREQ int = 198
	RESULT_ERROR_SYSMGR_NOT_SUPPORT     int = 199
	//删除数据对象失败的通用原因，如果明确是业务记录不存在，则用明确的错误码
	RESULT_ERROR_FAILED_INSERT_DATAITEM int = 200
	RESULT_ERROR_FAILED_UPDATE_DATAITEM int = 201
	RESULT_ERROR_FAILED_DEL_DATAITEM    int = 202
	RESULT_ERROR_DATA_INCONSISTENT      int = 203
	RESULT_ERROR_OPEN_DB                int = 204
	RESULT_ERROR_CLOSE_DB               int = 205
	RESULT_ERROR_SQL_OP                 int = 206
	//IP网络和通信相关错误, 300-399
	RESULT_ERROR_INVALID_IPADDR    int = 300
	RESULT_ERROR_INVALID_MACADDR   int = 301
	RESULT_ERROR_IP_CONFLICT       int = 302
	RESULT_ERROR_INVALID_PKT       int = 303
	RESULT_ERROR_INVALID_ARP_PKT   int = 304
	RESULT_ERROR_INVALID_DNS_PKT   int = 305
	RESULT_ERROR_INVALID_DHCP_PKT  int = 306
	RESULT_ERROR_FAILED_SEND_MSG   int = 307
	RESULT_ERROR_MSG_TOO_LONG      int = 308
	RESULT_ERROR_CONNECTION_CLOSED int = 309
	RESULT_ERROR_FAILED_GRPC_CALL  int = 310
	//SDN业务实现具体错误，500-599
	RESULT_ERROR_DEVICE_OFFLINE           int = 500
	RESULT_ERROR_DEVICE_NOT_EXIST         int = 501
	RESULT_ERROR_DEVICE_SHUTDOWN          int = 502
	RESULT_ERROR_CONNECTING_DEVICE        int = 503
	RESULT_ERROR_PORT_NOT_EXIST           int = 504
	RESULT_ERROR_TENANT_NOT_EXIST         int = 505
	RESULT_ERROR_NETWORK_NOT_EXIST        int = 506
	RESULT_ERROR_VRF_NOT_EXIST            int = 507
	RESULT_ERROR_SITE_NOT_EXIST           int = 508
	RESULT_ERROR_APPPOLICY_OP_NOT_SUPPORT int = 509
	RESULT_ERROR_VPN_LOGIN                int = 510
	RESULT_ERROR_OP_ABORTED               int = 511
	RESULT_ERROR_ASSET_EXCEEDED           int = 512
	RESULT_ERROR_PATH_NOT_FOUND           int = 550
	RESULT_ERROR_FAILED_OVSDB_OP          int = 551
	RESULT_ERROR_CONNECT_OVS_FAIL         int = 552
	RESULT_ERROR_OVS_ADD_PORT             int = 553
	RESULT_ERROR_OVS_DEL_PORT             int = 554
	//安全相关错误码，600-699
	RESULT_ERROR_INVALID_CERT              int = 600
	RESULT_ERROR_INVALID_PUBLIC_KEY        int = 601
	RESULT_ERROR_INVALID_PRIVATE_KEY       int = 602
	RESULT_ERROR_INVALID_USERNAME          int = 603
	RESULT_ERROR_INVALID_PASSWORD          int = 604
	RESULT_ERROR_INVALID_LICENSE_FILE      int = 605
	RESULT_ERROR_LICENSE_FUNC_MISSED       int = 606
	RESULT_ERROR_LICENSE_CAPACITY_EXCEEDED int = 607
	RESULT_ERROR_LICENSE_EXPIRED           int = 608
	RESULT_ERROR_AUTH_CHALLENGE            int = 610
	RESULT_ERROR_SESSION_EXPIRED           int = 611
	//NFV功能部件、实例相关错误，900-999
	RESULT_ERROR_START_VPN int = 900
	RESULT_ERROR_STOP_VPN  int = 901
	RESULT_ERROR_START_VFW int = 902
	RESULT_ERROR_STOP_VFW  int = 903
	RESULT_ERROR_START_AV  int = 904
	RESULT_ERROR_STOP_AV   int = 905
	// Errors for business logic
	RESULT_ERROR_OUTOF_CHARGE int = 1000
)
