package errcode

type RESULT int32

const (
	RESULT_SUCCESS RESULT = 0
	//系统通用错误，1-199
	RESULT_ERROR_COMMON              RESULT = 1
	RESULT_ERROR_NULL_POINTER        RESULT = 2
	RESULT_ERROR_NOT_FOUND           RESULT = 3
	RESULT_ERROR_ALREADY_EXIST       RESULT = 4
	RESULT_ERROR_OUTOF_MEMORY        RESULT = 5
	RESULT_ERROR_TIME_OUT            RESULT = 6
	RESULT_ERROR_FILE_NOT_FOUND      RESULT = 7
	RESULT_ERROR_FAILED_OPEN_FILE    RESULT = 8
	RESULT_ERROR_DISK_FULL           RESULT = 9
	RESULT_ERROR_NO_PERMISSION       RESULT = 10
	RESULT_ERROR_INVALID_PARAM       RESULT = 11
	RESULT_ERROR_CPU_OVERLOAD        RESULT = 12
	RESULT_ERROR_LOAD_MODULE         RESULT = 13
	RESULT_ERROR_INVALID_UUID_STRING RESULT = 14
	RESULT_ERROR_INVALID_DATE_FORMAT RESULT = 15
	RESULT_ERROR_FAILED_ENCODING     RESULT = 16
	RESULT_ERROR_FAILED_DECODING     RESULT = 17
	RESULT_ERROR_NOT_IMPLEMENTED     RESULT = 18
	RESULT_ERROR_SYSCALL_FAIL        RESULT = 19
	RESULT_ERROR_QUOTA_EXCEEDED      RESULT = 20
	RESULT_ERROR_NOT_INITIATED       RESULT = 21
	//Error for sysmgr,暂时保留，不应该给具体某个模块预留错误，而是给功能错误留错误码，未初始化则对所有的系统都应未初始化
	RESULT_ERROR_SYSMGR_NOT_INITED      RESULT = 196
	RESULT_ERROR_SYSMRG_UPDATEREQ       RESULT = 197
	RESULT_ERROR_SYSMRG_CANCELUPDATEREQ RESULT = 198
	RESULT_ERROR_SYSMGR_NOT_SUPPORT     RESULT = 199
	//删除数据对象失败的通用原因，如果明确是业务记录不存在，则用明确的错误码
	RESULT_ERROR_FAILED_INSERT_DATAITEM RESULT = 200
	RESULT_ERROR_FAILED_UPDATE_DATAITEM RESULT = 201
	RESULT_ERROR_FAILED_DEL_DATAITEM    RESULT = 202
	RESULT_ERROR_DATA_INCONSISTENT      RESULT = 203
	RESULT_ERROR_OPEN_DB                RESULT = 204
	RESULT_ERROR_CLOSE_DB               RESULT = 205
	RESULT_ERROR_SQL_OP                 RESULT = 206
	//IP网络和通信相关错误, 300-399
	RESULT_ERROR_INVALID_IPADDR    RESULT = 300
	RESULT_ERROR_INVALID_MACADDR   RESULT = 301
	RESULT_ERROR_IP_CONFLICT       RESULT = 302
	RESULT_ERROR_INVALID_PKT       RESULT = 303
	RESULT_ERROR_INVALID_ARP_PKT   RESULT = 304
	RESULT_ERROR_INVALID_DNS_PKT   RESULT = 305
	RESULT_ERROR_INVALID_DHCP_PKT  RESULT = 306
	RESULT_ERROR_FAILED_SEND_MSG   RESULT = 307
	RESULT_ERROR_MSG_TOO_LONG      RESULT = 308
	RESULT_ERROR_CONNECTION_CLOSED RESULT = 309
	RESULT_ERROR_FAILED_GRPC_CALL  RESULT = 310
	//SDN业务实现具体错误，500-599
	RESULT_ERROR_DEVICE_OFFLINE           RESULT = 500
	RESULT_ERROR_DEVICE_NOT_EXIST         RESULT = 501
	RESULT_ERROR_DEVICE_SHUTDOWN          RESULT = 502
	RESULT_ERROR_CONNECTING_DEVICE        RESULT = 503
	RESULT_ERROR_PORT_NOT_EXIST           RESULT = 504
	RESULT_ERROR_TENANT_NOT_EXIST         RESULT = 505
	RESULT_ERROR_NETWORK_NOT_EXIST        RESULT = 506
	RESULT_ERROR_VRF_NOT_EXIST            RESULT = 507
	RESULT_ERROR_SITE_NOT_EXIST           RESULT = 508
	RESULT_ERROR_APPPOLICY_OP_NOT_SUPPORT RESULT = 509
	RESULT_ERROR_VPN_LOGIN                RESULT = 510
	RESULT_ERROR_OP_ABORTED               RESULT = 511
	RESULT_ERROR_ASSET_EXCEEDED           RESULT = 512
	RESULT_ERROR_PATH_NOT_FOUND           RESULT = 550
	RESULT_ERROR_FAILED_OVSDB_OP          RESULT = 551
	RESULT_ERROR_CONNECT_OVS_FAIL         RESULT = 552
	RESULT_ERROR_OVS_ADD_PORT             RESULT = 553
	RESULT_ERROR_OVS_DEL_PORT             RESULT = 554
	//安全相关错误码，600-699
	RESULT_ERROR_INVALID_CERT              RESULT = 600
	RESULT_ERROR_INVALID_PUBLIC_KEY        RESULT = 601
	RESULT_ERROR_INVALID_PRIVATE_KEY       RESULT = 602
	RESULT_ERROR_INVALID_USERNAME          RESULT = 603
	RESULT_ERROR_INVALID_PASSWORD          RESULT = 604
	RESULT_ERROR_INVALID_LICENSE_FILE      RESULT = 605
	RESULT_ERROR_LICENSE_FUNC_MISSED       RESULT = 606
	RESULT_ERROR_LICENSE_CAPACITY_EXCEEDED RESULT = 607
	RESULT_ERROR_LICENSE_EXPIRED           RESULT = 608
	RESULT_ERROR_AUTH_CHALLENGE            RESULT = 610
	RESULT_ERROR_SESSION_EXPIRED           RESULT = 611
	RESULT_ERROR_USERNAME_LOCK             RESULT = 612
	//NFV功能部件、实例相关错误，900-999
	RESULT_ERROR_START_VPN RESULT = 900
	RESULT_ERROR_STOP_VPN  RESULT = 901
	RESULT_ERROR_START_VFW RESULT = 902
	RESULT_ERROR_STOP_VFW  RESULT = 903
	RESULT_ERROR_START_AV  RESULT = 904
	RESULT_ERROR_STOP_AV   RESULT = 905
	// Errors for business logic
	RESULT_ERROR_OUTOF_CHARGE RESULT = 1000
)

var RESULT_name = map[int32]string{
	0:    "SUCCESS",
	1:    "ERROR_COMMON",
	2:    "ERROR_NULL_POINTER",
	3:    "ERROR_NOT_FOUND",
	4:    "ERROR_ALREADY_EXIST",
	5:    "ERROR_OUTOF_MEMORY",
	6:    "ERROR_TIME_OUT",
	7:    "ERROR_FILE_NOT_FOUND",
	8:    "ERROR_FAILED_OPEN_FILE",
	9:    "ERROR_DISK_FULL",
	10:   "ERROR_NO_PERMISSION",
	11:   "ERROR_INVALID_PARAM",
	12:   "ERROR_CPU_OVERLOAD",
	13:   "ERROR_LOAD_MODULE",
	14:   "ERROR_INVALID_UUID_STRING",
	15:   "ERROR_INVALID_DATE_FORMAT",
	16:   "ERROR_FAILED_ENCODING",
	17:   "ERROR_FAILED_DECODING",
	18:   "ERROR_NOT_IMPLEMENTED",
	19:   "ERROR_SYSCALL_FAIL",
	20:   "ERROR_QUOTA_EXCEEDED",
	21:   "ERROR_NOT_INITIATED",
	196:  "ERROR_SYSMGR_NOT_INITED",
	197:  "ERROR_SYSMRG_UPDATEREQ",
	198:  "ERROR_SYSMRG_CANCELUPDATEREQ",
	199:  "ERROR_SYSMGR_NOT_SUPPORT",
	200:  "ERROR_FAILED_INSERT_DATAITEM",
	201:  "ERROR_FAILED_UPDATE_DATAITEM",
	202:  "ERROR_FAILED_DEL_DATAITEM",
	203:  "ERROR_DATA_INCONSISTENT",
	204:  "ERROR_OPEN_DB",
	205:  "ERROR_CLOSE_DB",
	206:  "ERROR_SQL_OP",
	300:  "ERROR_INVALID_IPADDR",
	301:  "ERROR_INVALID_MACADDR",
	302:  "ERROR_IP_CONFLICT",
	303:  "ERROR_INVALID_PKT",
	304:  "ERROR_INVALID_ARP_PKT",
	305:  "ERROR_INVALID_DNS_PKT",
	306:  "ERROR_INVALID_DHCP_PKT",
	307:  "ERROR_FAILED_SEND_MSG",
	308:  "ERROR_MSG_TOO_LONG",
	309:  "ERROR_CONNECTION_CLOSED",
	310:  "ERROR_FAILED_GRPC_CALL",
	500:  "ERROR_DEVICE_OFFLINE",
	501:  "ERROR_DEVICE_NOT_EXIST",
	502:  "ERROR_DEVICE_SHUTDOWN",
	503:  "ERROR_CONNECTING_DEVICE",
	504:  "ERROR_PORT_NOT_EXIST",
	505:  "ERROR_TENANT_NOT_EXIST",
	506:  "ERROR_NETWORK_NOT_EXIST",
	507:  "ERROR_VRF_NOT_EXIST",
	508:  "ERROR_SITE_NOT_EXIST",
	509:  "ERROR_APPPOLICY_OP_NOT_SUPPORT",
	510:  "ERROR_VPN_LOGIN",
	511:  "ERROR_OP_ABORTED",
	512:  "ERROR_ASSET_EXCEEDED",
	550:  "ERROR_PATH_NOT_FOUND",
	551:  "ERROR_FAILED_OVSDB_OP",
	552:  "ERROR_CONNECT_OVS_FAIL",
	553:  "ERROR_OVS_ADD_PORT",
	554:  "ERROR_OVS_DEL_PORT",
	600:  "ERROR_INVALID_CERT",
	601:  "ERROR_INVALID_PUBLIC_KEY",
	602:  "ERROR_INVALID_PRIVATE_KEY",
	603:  "ERROR_INVALID_USERNAME",
	604:  "ERROR_INVALID_PASSWORD",
	605:  "ERROR_INVALID_LICENSE_FILE",
	606:  "ERROR_LICENSE_FUNC_MISSED",
	607:  "ERROR_LICENSE_CAPACITY_EXCEEDED",
	608:  "ERROR_LICENSE_EXPIRED",
	610:  "ERROR_AUTH_CHALLENGE",
	611:  "ERROR_SESSION_EXPIRED",
	900:  "ERROR_START_VPN",
	901:  "ERROR_STOP_VPN",
	902:  "ERROR_START_VFW",
	903:  "ERROR_STOP_VFW",
	904:  "ERROR_START_AV",
	905:  "ERROR_STOP_AV",
	1000: "ERROR_OUTOF_CHARGE",
}

var RESULT_value = map[string]int32{
	"SUCCESS":                         0,
	"ERROR_COMMON":                    1,
	"ERROR_NULL_POINTER":              2,
	"ERROR_NOT_FOUND":                 3,
	"ERROR_ALREADY_EXIST":             4,
	"ERROR_OUTOF_MEMORY":              5,
	"ERROR_TIME_OUT":                  6,
	"ERROR_FILE_NOT_FOUND":            7,
	"ERROR_FAILED_OPEN_FILE":          8,
	"ERROR_DISK_FULL":                 9,
	"ERROR_NO_PERMISSION":             10,
	"ERROR_INVALID_PARAM":             11,
	"ERROR_CPU_OVERLOAD":              12,
	"ERROR_LOAD_MODULE":               13,
	"ERROR_INVALID_UUID_STRING":       14,
	"ERROR_INVALID_DATE_FORMAT":       15,
	"ERROR_FAILED_ENCODING":           16,
	"ERROR_FAILED_DECODING":           17,
	"ERROR_NOT_IMPLEMENTED":           18,
	"ERROR_SYSCALL_FAIL":              19,
	"ERROR_QUOTA_EXCEEDED":            20,
	"ERROR_NOT_INITIATED":             21,
	"ERROR_SYSMGR_NOT_INITED":         196,
	"ERROR_SYSMRG_UPDATEREQ":          197,
	"ERROR_SYSMRG_CANCELUPDATEREQ":    198,
	"ERROR_SYSMGR_NOT_SUPPORT":        199,
	"ERROR_FAILED_INSERT_DATAITEM":    200,
	"ERROR_FAILED_UPDATE_DATAITEM":    201,
	"ERROR_FAILED_DEL_DATAITEM":       202,
	"ERROR_DATA_INCONSISTENT":         203,
	"ERROR_OPEN_DB":                   204,
	"ERROR_CLOSE_DB":                  205,
	"ERROR_SQL_OP":                    206,
	"ERROR_INVALID_IPADDR":            300,
	"ERROR_INVALID_MACADDR":           301,
	"ERROR_IP_CONFLICT":               302,
	"ERROR_INVALID_PKT":               303,
	"ERROR_INVALID_ARP_PKT":           304,
	"ERROR_INVALID_DNS_PKT":           305,
	"ERROR_INVALID_DHCP_PKT":          306,
	"ERROR_FAILED_SEND_MSG":           307,
	"ERROR_MSG_TOO_LONG":              308,
	"ERROR_CONNECTION_CLOSED":         309,
	"ERROR_FAILED_GRPC_CALL":          310,
	"ERROR_DEVICE_OFFLINE":            500,
	"ERROR_DEVICE_NOT_EXIST":          501,
	"ERROR_DEVICE_SHUTDOWN":           502,
	"ERROR_CONNECTING_DEVICE":         503,
	"ERROR_PORT_NOT_EXIST":            504,
	"ERROR_TENANT_NOT_EXIST":          505,
	"ERROR_NETWORK_NOT_EXIST":         506,
	"ERROR_VRF_NOT_EXIST":             507,
	"ERROR_SITE_NOT_EXIST":            508,
	"ERROR_APPPOLICY_OP_NOT_SUPPORT":  509,
	"ERROR_VPN_LOGIN":                 510,
	"ERROR_OP_ABORTED":                511,
	"ERROR_ASSET_EXCEEDED":            512,
	"ERROR_PATH_NOT_FOUND":            550,
	"ERROR_FAILED_OVSDB_OP":           551,
	"ERROR_CONNECT_OVS_FAIL":          552,
	"ERROR_OVS_ADD_PORT":              553,
	"ERROR_OVS_DEL_PORT":              554,
	"ERROR_INVALID_CERT":              600,
	"ERROR_INVALID_PUBLIC_KEY":        601,
	"ERROR_INVALID_PRIVATE_KEY":       602,
	"ERROR_INVALID_USERNAME":          603,
	"ERROR_INVALID_PASSWORD":          604,
	"ERROR_INVALID_LICENSE_FILE":      605,
	"ERROR_LICENSE_FUNC_MISSED":       606,
	"ERROR_LICENSE_CAPACITY_EXCEEDED": 607,
	"ERROR_LICENSE_EXPIRED":           608,
	"ERROR_AUTH_CHALLENGE":            610,
	"ERROR_SESSION_EXPIRED":           611,
	"ERROR_START_VPN":                 900,
	"ERROR_STOP_VPN":                  901,
	"ERROR_START_VFW":                 902,
	"ERROR_STOP_VFW":                  903,
	"ERROR_START_AV":                  904,
	"ERROR_STOP_AV":                   905,
	"ERROR_OUTOF_CHARGE":              1000,
}
